import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Footer from "@/components/Footer";
import { UserProvider } from "@auth0/nextjs-auth0/client";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Caseoh Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
      <body
        className={cn(
          "flex flex-col placeholder:min-h-screen bg-background font-sans antialiased ",
          fontSans.variable
        )}
      >
        <Navbar />
        <Hero />

        <div className="container mx-auto flex-1 py-10">{children}</div>
        <Footer />
        </body>
      </UserProvider>
    </html>
  );
}
